### ISSUE TITLE
& {...} 形式的会有问题

### ISSUE THREAD

**Issue by TinyWisp** [fnick851/vue-use-css#1]
如果css是这样的，会有问题

```css
& {
  font-size: 14px;
}
```

不会变成下面这种形式
```css
[data-css-scope='1'] {
  font-size: 14px;
}
```

**Comment by fnick851** [comment]
@TinyWisp 

不太明白你的意思？

“&” 不是一个有效的 CSS 选择器。
所以这个-
```css
& {
  font-size: 14px;
}
```
本身就是错误的CSS。
